;; DO NOT EDIT THIS FILE DIRECTLY!
;; This file is auto-generated from Applications.org

(("default" . ((user-emacs-directory . "~/mydoom")
               (env . (("DOOMDIR" . "~/.doom.d")))))
 ("lab" . ((user-emacs-directory . "~/backupdoom")
               (env . (("DOOMDIR" . "~/lab")))))
 ("backup" . ((user-emacs-directory . "~/backupdoom")
               (env . (("DOOMDIR" . "~/testingThings"))))))
