;; DO NOT EDIT THIS FILE DIRECTLY!
;; This file is auto generated from Applications.org

(("default" . ((user-emacs-directory . "~/mydoom")
               (env . (("DOOMDIR" . "~/.doom.d")))))
 ("backup" . ((user-emacs-directory . "~/backupdoom")
               (env . (("DOOMDIR" . "~/testingThings"))))))
