#!/usr/bin/env bash
# DO NOT EDIT THIS FILE DIRECTLY!
# This file is auto generated from Applications.org

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && brew upgrade
brew tap caskroom/cask 2> /dev/null
brew cask upgrade

brew install node # This will install npm as well

brew tap d12frosted/emacs-plus
# brew install emacs-plus # install the latest version of Emacs (as of writing Emacs 27)
# brew install emacs-plus@26 [options] # install Emacs 26
# brew install emacs-plus@27 [options] # install Emacs 27
brew install emacs-plus@28 # install Emacs 28

ln -s /usr/local/opt/emacs-plus/Emacs.app /Applications/Emacs.app

# Check for ~/.emacs.d if exists move it before cloning the code
if [ -d "$HOME/.emacs.d" ]
   then
       mv "$HOME/.emacs.d" "$HOME/.emacs.d.bak"
fi

git clone git@github.com:plexus/chemacs2.git ~/.emacs.d

# required dependencies
brew install git ripgrep
# optional dependencies
brew install coreutils fd
# Installs clang
xcode-select --install

git clone git@github.com:hlissner/doom-emacs.git ~/mydoom

brew install aspell
npm install -g marked
brew install jq
brew install shellcheck

export PATH="$HOME/mydoom/bin:$PATH"
doom install

cp -a $HOME/mydoom $HOME/backupdoom

brew install vscode
brew cask install docker
brew install firefox
brew install chrome

brew install slack
