#!/usr/bin/env bash
# DO NOT EDIT THIS FILE DIRECTLY!
# This file is auto-generated from Applications.org

sudo apt install git

curl https://raw.githubusercontent.com/lyze/posh-git-sh/blob/master/git-prompt.sh > ~/git-prompt.sh

wget https://dot.net/v1/dotnet-install.sh -P ./bin
export PATH=$PATH:$PWD/bin
dotnet-install.sh -c 6.0
#dotnet-install.sh -c 5.0

# Uncomment to install mono
# sudo apt install gnupg ca-certificates
# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
# echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
# sudo apt update

# sudo apt install mono-complete

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
# Executing this so we don't need a new shell
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

nvm install --lts

alias python=python3

sudo snap install go --classic

export PATH="$HOME/go/bin:$PATH"

go install github.com/x-motemen/gore/cmd/gore@latest
go install github.com/stamblerre/gocode@latest
go install golang.org/x/tools/cmd/godoc@latest
go install golang.org/x/tools/cmd/goimports@latest
go install golang.org/x/tools/cmd/gorename@latest
go install golang.org/x/tools/cmd/guru@latest
go install github.com/cweill/gotests/gotests@latest
go install github.com/fatih/gomodifytags@latest
go install golang.org/x/tools/gopls@latest
go install mvdan.cc/sh/v3/cmd/shfmt@latest

snap install emacs --classic

# The default location of the .emacs.d directory should only exist if you open emacs after installation.
if [ -d "$HOME/.emacs.d" ]
   then
       mv "$HOME/.emacs.d" "$HOME/.emacs.d.bak"
fi

git clone https://github.com/plexus/chemacs2.git ~/.emacs.d

sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install git

sudo apt install ripgrep fd-find

git clone https://github.com/hlissner/doom-emacs.git ~/mydoom
sudo apt install editorconfig
npm install -g marked
sudo apt install pandoc
sudo apt install jq
sudo apt install shellcheck
sudo apt install graphviz

export PATH="$HOME/mydoom/bin:$PATH"
doom install

cp -a $HOME/mydoom $HOME/backupdoom

curl https://raw.githubusercontent.com/nagygergo/jetbrains-toolbox-install/master/jetbrains-toolbox.sh > jetbrains-toolbox.sh

./jetbrains-toolbox.sh

curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube

sudo apt-get install -y podman

sudo snap install slack --classic

sudo snap install discord
